### ISSUE TITLE
Helm chart does not support environment variables

### ISSUE THREAD

**Issue by blagerweij** [piiano/helm-charts#13]
We are using Hashicorp Vault to inject secrets into the deployment workloads. However, the current template does not support this.

What we would like is to configure something like this in values.yaml:

```
pvault:
  env:
  - name: PVAULT_DB_HOSTNAME
    value: ${vault:secrets/data/database/users/piianodb#database}
```
